token:
  expiration_time: 864000022
  secret: '{cipher}AQAiM+suOJU7Iy8Q+UiBfCIK79+jZ40mPKRHVrEN4VCcRAXuaWVH+VlXSQZGT2xD0Tk5m4Mq7+u8a7ip/cViX8QNYqHf+Ul4RDm9uyYkFp+5A6OI4iGlXTrr8OvImtTkGz3H1A9HY5bXVrz/TQy8XqTSVUsHW7k6V+/U9Bd9E7kecfAuVDrS5P+Txb13grRB480F1hJbpnFDaX7xPoZvAIo3xpjnNNM9VIwJkwDX7XKqBGfg9E8sKJcIAkEbaLakhcBjm6BtIts4uvnzz7ikLiXIk64p74gCAnWE5b5W1ymS4WftgHaHuLy5zaxFLkH1pqnPm6LIhfLXbF4AtVFUDfH3xGKdT4jANmwzY14elecQAICGCwXbJxoHZ4Ii/SN8V/SyDVDBIordXp3jTE9zcWX2'

gateway:
  ip: 0.0.0.0